// <auto-generated />
using System;
using KeyvanSafe.Shared.EntityFramework.Configs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyvanSafe.Shared.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Claims.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Permissions.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6243),
                            Name = "UserManagement",
                            Title = "مدیریت کاربران",
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6246),
                            Value = "identity.users.command"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6252),
                            Name = "RoleManagement",
                            Title = "مدیریت نقش‌ها",
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6253),
                            Value = "identity.roles.command"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6256),
                            Name = "ClaimManagement",
                            Title = "مدیریت دسترسی ها",
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6257),
                            Value = "identity.claims.command"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6260),
                            Name = "UserView",
                            Title = "نمایش  مدیریت کاربران",
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6261),
                            Value = "identity.users.query"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6263),
                            Name = "RoleView",
                            Title = "نمایش  مدیریت نقش ها",
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6265),
                            Value = "identity.roles.query"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6269),
                            Name = "ClaimView",
                            Title = "نمایش  مدیریت دسترسی ها",
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6271),
                            Value = "identity.claims.query"
                        });
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 147, DateTimeKind.Local).AddTicks(3626),
                            Title = "Owner",
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 147, DateTimeKind.Local).AddTicks(3628)
                        });
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Roles.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId", "PermissionId", "Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            Id = 0,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6352),
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6354)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            Id = 0,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6425),
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6427)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3,
                            Id = 0,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6430),
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6431)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4,
                            Id = 0,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6433),
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6435)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5,
                            Id = 0,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6437),
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6438)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6,
                            Id = 0,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6441),
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6443)
                        });
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMobileConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPasswordChangeTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "BNBURMMZA41CB27XQQ9BAVQPJTBVR41T",
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6039),
                            Email = "bamdadtabari@outlook.com",
                            FailedLoginCount = 0,
                            FirstName = "Bamdad",
                            FullName = "Bamdad Tabari",
                            IsLockedOut = false,
                            IsMobileConfirmed = false,
                            LastName = "Tabari",
                            LastPasswordChangeTime = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6028),
                            Mobile = "09301724389",
                            PasswordHash = "lpMIfapII2rgoO4V/isM9sj+NJjWZb9n8YLZQRFJNxg=.Rn2VMN+QnKfux9uWOOOrTQ==",
                            SecurityStamp = "HF55X2EXOEZAG6BEYB6PHR1HR3TXW2FDY8ZTS0F8QBYUYKKCA5LKX1B6LXD5VELV",
                            State = "Active",
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 156, DateTimeKind.Local).AddTicks(6041),
                            UserName = "Illegible_Owner"
                        });
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Users.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId", "Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            Id = 0,
                            CreatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 147, DateTimeKind.Local).AddTicks(3562),
                            UpdatedAt = new DateTime(2023, 8, 16, 13, 34, 47, 147, DateTimeKind.Local).AddTicks(3594)
                        });
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Claims.Claim", b =>
                {
                    b.HasOne("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Users.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Roles.RolePermission", b =>
                {
                    b.HasOne("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Permissions.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Roles.Role", "Role")
                        .WithMany("RolePermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Users.UserRole", b =>
                {
                    b.HasOne("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Permissions.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Roles.Role", b =>
                {
                    b.Navigation("RolePermission");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("KeyvanSafe.Shared.EntityFramework.Entities.Identity.Users.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
